# Generated by Django 6.0.6 on 2026-06-10 15:55

import django.db.models.deletion
import fxsharing.shares.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('exception_class', models.CharField(max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('queue', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(default=fxsharing.shares.models.generate_shortcode, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('under_review', 'Under Review (User Reported)'), ('flagged_by_system', 'Flagged by System'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_shares', to='shares.share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=4000)),
                ('safety_status', models.CharField(choices=[('unknown', 'Unknown'), ('safe', 'Safe'), ('unsafe', 'Unsafe')], default='unknown', max_length=16)),
                ('preview_title', models.CharField(blank=True, max_length=255)),
                ('preview_description', models.TextField(null=True)),
                ('preview_image_url', models.URLField(max_length=2048, null=True)),
                ('favicon_url', models.URLField(blank=True, max_length=2048)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='shares.share')),
            ],
        ),
    ]
