# Generated by Django 6.0.6 on 2026-06-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.CharField(choices=[('tabs', 'Multi selected tabs'), ('bookmarks', 'Bookmark folder'), ('tab_group', 'Tab group')], default='bookmarks', max_length=16),
            preserve_default=False,
        ),
    ]
