# Generated by Django 6.0.3 on 2026-03-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_share_nested_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='nested_share',
            new_name='parent_share',
        ),
    ]
