# Generated by Django 6.0.3 on 2026-03-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_rename_nested_share_share_parent_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='parent_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_shares', to='shares.share'),
        ),
    ]
