# Generated by Django 6.0.3 on 2026-03-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_alter_share_parent_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='fxa_id',
        ),
    ]
