# Generated by Django 6.0.3 on 2026-04-27 22:58

import fxsharing.shares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_remove_share_fxa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='preview_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='link',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='link',
            name='preview_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='safety_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('safe', 'Safe'), ('unsafe', 'Unsafe')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='share',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='share',
            name='shortcode',
            field=models.CharField(default=fxsharing.shares.models.generate_shortcode, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='share',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('flagged', 'Flagged')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=4000),
        ),
    ]
