# Generated by Django 6.0.3 on 2026-04-23 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_remove_share_fxa_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
