# Generated by Django 6.0.4 on 2026-05-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_share_user'),
        ('shares', '0006_update_share_and_link_models'),
    ]

    operations = [
    ]
