# Generated by Django 6.0.4 on 2026-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shares", "0007_merge_20260504_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="favicon_image_url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="preview_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="preview_image_url",
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
