# Generated by Django 6.0.4 on 2026-05-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_merge_20260504_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
