# Generated by Django 6.0.4 on 2026-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_merge_20260504_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('under_review', 'Under Review (User Reported)'), ('flagged_by_system', 'Flagged by System'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=32),
        ),
    ]
