# Generated by Django 6.0.4 on 2026-05-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0008_link_favicon_url'),
        ('shares', '0009_migrate_deleted_status_to_deleted_at'),
    ]

    operations = [
    ]
