# Generated by Django 6.0.6 on 2026-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_deadlettertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='preview_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='preview_image_url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
