# Generated by Django 6.0.4 on 2026-06-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_deadlettertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='idempotency_key',
        ),
    ]
