# Generated by Django 6.0.4 on 2026-06-04 18:01

import fxsharing.shares.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_deadlettertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(default=fxsharing.shares.models.generate_shortcode, max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=4000)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
