# Generated by Django 6.0.4 on 2026-06-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shares", "0008_link_favicon_image_url_and_more"),
        ("shares", "0011_deadlettertask"),
    ]

    operations = []
