# Generated by Django 6.0.4 on 2026-06-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shares", "0012_merge_20260604_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="favicon_image_url",
        ),
    ]
