# Generated by Django 6.0.4 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badness_counter",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
