name: Deploy to MozCloud environment
on:
  push:
    branches: ['**']
    tags:
      - 'v20[0-9][0-9].[01][0-9].[0-3][0-9]'
      - 'v20[0-9][0-9].[01][0-9].[0-3][0-9]-[0-9]'
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-to-gar.yml
    secrets: inherit
    if: >
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/tags/') ||
      github.event_name == 'workflow_dispatch'
    with:
      image_tag_metadata: >-
        ${{ inputs.environment ||
            (startsWith(github.ref, 'refs/tags/') && 'prod') ||
            'dev' }}
